session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: dpm-eng
    fr: dpm-french
    it: dpm-ita
  domains:
    en: ''
    fr: ''
    it: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
